// <auto-generated />
using System;
using LogisticsApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503164802_AddFullOrderInfo")]
    partial class AddFullOrderInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogisticsApp.Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountOfFuelPoured")
                        .HasColumnType("float");

                    b.Property<string>("BriefDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrewMember1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrewMember2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrewMember3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("float");

                    b.Property<double>("FuelOnFinish")
                        .HasColumnType("float");

                    b.Property<double>("FuelOnStart")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfRefills")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RouteLengthKm")
                        .HasColumnType("float");

                    b.Property<string>("TypeOfCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatercraftModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatercraftNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightTons")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfFuelPoured = 0.0,
                            BriefDescription = "Перевезення вугілля, баржа 1",
                            CrewMember1 = "",
                            CrewMember2 = "",
                            CrewMember3 = "",
                            CustomerName = "",
                            Destination = "",
                            FuelConsumption = 0.0,
                            FuelOnFinish = 0.0,
                            FuelOnStart = 0.0,
                            NumberOfRefills = 0,
                            OrderNumber = "ORD-001",
                            RouteLengthKm = 0.0,
                            TypeOfCargo = "",
                            WatercraftModel = "",
                            WatercraftNumber = "",
                            WeightTons = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AmountOfFuelPoured = 0.0,
                            BriefDescription = "Бункерування буксира 'Богатир'",
                            CrewMember1 = "",
                            CrewMember2 = "",
                            CrewMember3 = "",
                            CustomerName = "",
                            Destination = "",
                            FuelConsumption = 0.0,
                            FuelOnFinish = 0.0,
                            FuelOnStart = 0.0,
                            NumberOfRefills = 0,
                            OrderNumber = "ORD-002",
                            RouteLengthKm = 0.0,
                            TypeOfCargo = "",
                            WatercraftModel = "",
                            WatercraftNumber = "",
                            WeightTons = 0.0
                        },
                        new
                        {
                            Id = 3,
                            AmountOfFuelPoured = 0.0,
                            BriefDescription = "Транспортування контейнерів",
                            CrewMember1 = "",
                            CrewMember2 = "",
                            CrewMember3 = "",
                            CustomerName = "",
                            Destination = "",
                            FuelConsumption = 0.0,
                            FuelOnFinish = 0.0,
                            FuelOnStart = 0.0,
                            NumberOfRefills = 0,
                            OrderNumber = "ORD-003",
                            RouteLengthKm = 0.0,
                            TypeOfCargo = "",
                            WatercraftModel = "",
                            WatercraftNumber = "",
                            WeightTons = 0.0
                        },
                        new
                        {
                            Id = 4,
                            AmountOfFuelPoured = 0.0,
                            BriefDescription = "Технічне обслуговування екіпажу",
                            CrewMember1 = "",
                            CrewMember2 = "",
                            CrewMember3 = "",
                            CustomerName = "",
                            Destination = "",
                            FuelConsumption = 0.0,
                            FuelOnFinish = 0.0,
                            FuelOnStart = 0.0,
                            NumberOfRefills = 0,
                            OrderNumber = "ORD-004",
                            RouteLengthKm = 0.0,
                            TypeOfCargo = "",
                            WatercraftModel = "",
                            WatercraftNumber = "",
                            WeightTons = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
