// <auto-generated />
using System;
using LogisticsApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503170208_AddFullOrderInfo2")]
    partial class AddFullOrderInfo2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogisticsApp.Server.Models.CrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CrewMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Іванов І.І. (Капітан)",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров П.П. (Механік)",
                            OrderId = 1
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров С.С. (Матрос)",
                            OrderId = 1
                        });
                });

            modelBuilder.Entity("LogisticsApp.Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountOfFuelPoured")
                        .HasColumnType("float");

                    b.Property<string>("BriefDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("float");

                    b.Property<double>("FuelOnFinish")
                        .HasColumnType("float");

                    b.Property<double>("FuelOnStart")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfRefills")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RouteLengthKm")
                        .HasColumnType("float");

                    b.Property<string>("TypeOfCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatercraftModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WatercraftNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightTons")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfFuelPoured = 0.0,
                            BriefDescription = "Перевезення вугілля",
                            CustomerName = "ТОВ ВугілляПром",
                            DateFinish = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Порт А",
                            FuelConsumption = 200.0,
                            FuelOnFinish = 800.0,
                            FuelOnStart = 1000.0,
                            NumberOfRefills = 0,
                            OrderNumber = "ORD-001",
                            RouteLengthKm = 0.0,
                            TypeOfCargo = "Вугілля",
                            WatercraftModel = "Буксир-штовхач",
                            WatercraftNumber = "БШ-45",
                            WeightTons = 500.0
                        });
                });

            modelBuilder.Entity("LogisticsApp.Server.Models.CrewMember", b =>
                {
                    b.HasOne("LogisticsApp.Server.Models.Order", "Order")
                        .WithMany("Crew")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LogisticsApp.Server.Models.Order", b =>
                {
                    b.Navigation("Crew");
                });
#pragma warning restore 612, 618
        }
    }
}
