// <auto-generated />
using LogisticsApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticsApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503163034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogisticsApp.Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BriefDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BriefDescription = "Перевезення вугілля, баржа 1",
                            OrderNumber = "ORD-001"
                        },
                        new
                        {
                            Id = 2,
                            BriefDescription = "Бункерування буксира 'Богатир'",
                            OrderNumber = "ORD-002"
                        },
                        new
                        {
                            Id = 3,
                            BriefDescription = "Транспортування контейнерів",
                            OrderNumber = "ORD-003"
                        },
                        new
                        {
                            Id = 4,
                            BriefDescription = "Технічне обслуговування екіпажу",
                            OrderNumber = "ORD-004"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
